### ISSUE TITLE
[BUG] Editor Crash

### ISSUE THREAD

**Issue by andrewharn** [3ddelano/godot-editor-discord-presence#10]
**Describe the bug**
Editor crashes once enabling the plugin and focusing Discord Canary. This happened again once I re-opened the editor.

**To Reproduce**
1. Go to AssetLib.
2. Download the plugin.
3. Enable the plugin.
4. Focus Discord Canary.

**Expected behavior**
The plugin to work normally I guess?

**Screenshots**
![image](https://user-images.githubusercontent.com/86312394/211859293-906f7d98-e066-4d92-b296-a04b1671240b.png)
![image](https://user-images.githubusercontent.com/86312394/211869268-9adb0d2f-134d-42c1-92b9-ea25ce1e8e0e.png)

**Desktop**
 - OS: Windows 8.1
 - Plugin Version: 1.2.5
 - Godot Version:  3.5

**Comment by 3ddelano** [comment]
Seems to be a threads issue, which is fixed after updating Discord-RPC-GDScript to v.1.1.1. You can try the latest version of the plugin [v.1.2.5](https://github.com/3ddelano/godot-editor-discord-presence/releases/tag/1.2.5)
