### ISSUE TITLE
Port to Godot 4?

### ISSUE THREAD

**Issue by Coder2195** [3ddelano/godot-editor-discord-presence#12]
**Is your feature request related to a problem? Please describe.**
Godot 4 doesn't support

**Describe the solution you'd like**
To support Godot 4, as Godot 4 has released to stable.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

## Checklist

- [ x] I have checked for duplicate feature requests.
- [ x] I have provided a detailed description of the enhancement.

**Comment by 3ddelano** [comment]
Godot 4 support can be tracked here [Godot 4 PR](https://github.com/3ddelano/godot-editor-discord-presence/pull/11)
