### ISSUE TITLE
[BUG] Godot 4

### ISSUE THREAD

**Issue by BlurrySquire** [3ddelano/godot-editor-discord-presence#13]
**Describe the bug**
When adding the plugin in Godot 4.0.2 , you get a lot of errors with the ``plugin.gd`` file.

**To Reproduce**
1. Open Godot 4.0.2, and create a new project.
2. Add the addon to the new project.
3. Attempt to enable to addon (fails), and then check ``plugin.gd`` file in the discord presence folder.
4. You can now see the many errors and why it does not work.

**Expected behavior**
The addon/plugin to work with Godot 4.0.2.

**Screenshots**
![image](https://github.com/3ddelano/godot-editor-discord-presence/assets/114335081/9efe6e26-cf26-4686-bb26-9d7d32fdc348)
![image](https://github.com/3ddelano/godot-editor-discord-presence/assets/114335081/ac20af63-7a85-4fc0-8fc7-98236f887c86)
I removed the random ``tool`` at the top:
![image](https://github.com/3ddelano/godot-editor-discord-presence/assets/114335081/a5f02c83-0e79-459e-a680-f8cd3726c6e9)

**Desktop (please complete the following information):**
 - Plugin Version: [e.g. 1.2.5]
 - Godot Version:  [e.g. 4.0.2]

**Additional context**

## Checklist

- [x] I have checked for duplicate issues.
- [x] I have provided a detailed description of the issue.
- [x] I have provided reproduction steps (if applicable).

**Comment by 3ddelano** [comment]
This is expected. The plugin currently is only for Godot 3.x as such it cannot be used in Godot 4.x. A port to Godot 4 is underway. You can see the progress here #11
