### ISSUE TITLE
[BUG] Attempt to call function "new" in base 'Nativescript'

### ISSUE THREAD

**Issue by Piras314** [3ddelano/godot-editor-discord-presence#4]
**Error after adding the add-on to my game**
The game gives an error right after I added it in the Output tab

**Steps To Reproduce**
Steps to reproduce the behaviour:
1. Enable the add-on on a MacBook or maybe Linux too

**Expected behaviour**
I expected it not to have bugs...

**Screenshots**
![image](https://user-images.githubusercontent.com/92357316/150666092-2c6e6e4c-b5b1-475f-9335-0fd3595e0d3a.png)

**Desktop:**
 - OS: MacOs
 - Plugin Version: 1.2.3
 - Godot Version:  3.4.2

**Additional context**
I'm using an M1 MacBook Air from 2020

**Comment by Piras314** [comment]
AHA! It isn't compiled for aarch64 for unix only x86_64 for some reason
![image](https://user-images.githubusercontent.com/92357316/150666236-1b2905bd-a0d8-49df-9b74-b9ae447a5828.png)

**Comment by Piras314** [comment]
I'm building it for aarch64 macOS and I'll create a pull request once that's done.

**Comment by Piras314** [comment]
I still can't seem to do it...

**Comment by 3ddelano** [comment]
The plugin itself is cross-platform but needs a 3rd party addon called Godot-UnixSocket available here [Github repo](https://github.com/Abdera7mane/Godot-UnixSocket)
As far as I know it has only been compiled for x64 bit linux and macos.
