### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dweremeichik** [3ddelano/godot-editor-discord-presence#5]
Just a heads up, it looks like ~~the two~~ one of the projects that this is based off of has no license.

**Comment by 3ddelano** [comment]
Do I need to add that in the license as well?

**Comment by dweremeichik** [comment]
No, it means that they need to add a license to their project otherwise no one is licensed to use it. I will open up issues with them. It's really just a technicality.

**Comment by dweremeichik** [comment]
Fixed upstream
