### ISSUE TITLE
Option to display Project icon in the Discord preview

### ISSUE THREAD

**Issue by Mickeon** [3ddelano/godot-editor-discord-presence#6]
The Discord game icon changing depending on what window is open is an outstandingly cool touch, but I personally don't find them too "eyecatching", so to speak.

![image](https://user-images.githubusercontent.com/66727710/152375406-4111dd39-4f58-4cf6-b700-08a749532fd1.png)

As an additional option, I think it'd be amazing to display the Project icon, or a custom icon entirely, if the Discord Rich Presence API would even support such a thing.

**Comment by 3ddelano** [comment]
As far as I know this is not possible since these icons have to be uploaded to the Discord Developer page and are cached.

**Comment by 3ddelano** [comment]
The only way would be that the user has to make a Discord rich presence application and upload the images they want and then change the Application Id in the plugin.
