### ISSUE TITLE
[BUG] Console error 'spam' when using other editor based plugins

### ISSUE THREAD

**Issue by zaknafean** [3ddelano/godot-editor-discord-presence#7]
**Describe the bug**
I'm only sure this works with one plugin, but I think the potential is there to mess with others too. When using the [Dialgoic](https://github.com/coppolaemilio/dialogic) plugin, and clicking on the Editor tab it creates, an error is thrown at line 250 in plugin.gd. This happens every time you switch to the tab.

![image](https://user-images.githubusercontent.com/7741797/164074352-fd83ce3a-6bf4-4455-a5e5-0c2269688198.png)
![image](https://user-images.githubusercontent.com/7741797/164073967-6b955bd8-84e0-4a66-9ff6-1e071b0a2840.png)

**To Reproduce**
1. Use a plugin that adds an editor feature (like Dialogic)
2. Click on the tab
3. Observe the console output error every time you click over to it

**Expected behavior**
No errors to appear in the console. Its not a big issue, not a crash or anything, but it is very annoying and if more editor plugins become popular it could get pretty messy.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin Version: 1.2.4
 - Godot Version:  3.4.4

**Additional context**

## Checklist

- [x] I have checked for duplicate issues.
- [x] I have provided a detailed description of the issue.
- [x] I have provided reproduction steps (if applicable).

**Comment by 3ddelano** [comment]
I'll look into it. Thanks!

**Comment by 3ddelano** [comment]
@zaknafean Thanks for this issue. Its been fixed in [83522b0](https://github.com/3ddelano/godot-editor-discord-presence/commit/83522b0862ce46de023ddb37f4fe8aa7373aa929)
